appPlayer/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'welcome/index'

  
  resources :players
  root 'welcome#index'    
  

end

appPlayer/app/models/atribute.rb
class Atribute < ActiveRecord::Base
  belongs_to :player
end

appPlayer/app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :player
end

appPlayer/app/models/player.rb
class Player < ActiveRecord::Base
    
    has_one :atribute
    has_one :feature

    accepts_nested_attributes_for :atribute
    accepts_nested_attributes_for :feature
    
    def self.search(query)
	where("name like ?","%#{query}%")
    end
end

appPlayer/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

appPlayer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

appPlayer/app/controllers/atributes_controller.rb
class AtributesController < ApplicationController
  before_action :set_atribute, only: [:show, :edit, :update, :destroy]

  # GET /atributes
  # GET /atributes.json
  def index
    @atributes = Atribute.all
  end

  # GET /atributes/1
  # GET /atributes/1.json
  def show
  end

  # GET /atributes/new
  def new
    @atribute = Atribute.new
  end

  # GET /atributes/1/edit
  def edit
  end

  # POST /atributes
  # POST /atributes.json
  def create
    @atribute = Atribute.new(atribute_params)

    respond_to do |format|
      if @atribute.save
        format.html { redirect_to @atribute, notice: 'Atribute was successfully created.' }
        format.json { render :show, status: :created, location: @atribute }
      else
        format.html { render :new }
        format.json { render json: @atribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atributes/1
  # PATCH/PUT /atributes/1.json
  def update
    respond_to do |format|
      if @atribute.update(atribute_params)
        format.html { redirect_to @atribute, notice: 'Atribute was successfully updated.' }
        format.json { render :show, status: :ok, location: @atribute }
      else
        format.html { render :edit }
        format.json { render json: @atribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atributes/1
  # DELETE /atributes/1.json
  def destroy
    @atribute.destroy
    respond_to do |format|
      format.html { redirect_to atributes_url, notice: 'Atribute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atribute
      @atribute = Atribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atribute_params
      params.require(:atribute).permit(:Forca, :Reflexo, :Saude, :Intuicao, :Vontade, :Presenca, :player_id)
    end
end

appPlayer/app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :set_feature, only: [:show, :edit, :update, :destroy]

  # GET /features
  # GET /features.json
  def index
    @features = Feature.all
  end

  # GET /features/1
  # GET /features/1.json
  def show
  end

  # GET /features/new
  def new
    @feature = Feature.new
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(feature_params)

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render :show, status: :created, location: @feature }
      else
        format.html { render :new }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1
  # PATCH/PUT /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { render :show, status: :ok, location: @feature }
      else
        format.html { render :edit }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature.destroy
    respond_to do |format|
      format.html { redirect_to features_url, notice: 'Feature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_params
      params.require(:feature).permit(:equipamentos, :proficiencias, :player_id)
    end
end

appPlayer/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /players
  # GET /players.json
  def index
    if params[:search]
	@players = Player.search(params[:search])    
    else
	@players = Player.all
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
    @player.build_atribute
    @player.build_feature
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'O personagem foi criado com sucesso!' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'O personagem foi atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'O personagem foi removido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :especie, :altura, :peso, :gravidade, :sexo, :idade, :atribute_attributes => [:Forca, :Reflexo, :Saude, :Intuicao, :Vontade, :Presenca], :feature_attributes => [:equipamentos, :proficiencias])
    end
end

appPlayer/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

appPlayer/app/helpers/application_helper.rb
module ApplicationHelper
end

appPlayer/app/helpers/atributes_helper.rb
module AtributesHelper
end

appPlayer/app/helpers/features_helper.rb
module FeaturesHelper
end

appPlayer/app/helpers/players_helper.rb
module PlayersHelper
end

appPlayer/app/helpers/welcome_helper.rb
module WelcomeHelper
end

appPlayer/app/views/atributes/_form.html.erb
<%= form_for(@atribute) do |f| %>
  <% if @atribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@atribute.errors.count, "error") %> prohibited this atribute from being saved:</h2>

      <ul>
      <% @atribute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Forca %><br>
    <%= f.number_field :Forca %>
  </div>
  <div class="field">
    <%= f.label :Reflexo %><br>
    <%= f.number_field :Reflexo %>
  </div>
  <div class="field">
    <%= f.label :Saude %><br>
    <%= f.number_field :Saude %>
  </div>
  <div class="field">
    <%= f.label :Intuicao %><br>
    <%= f.number_field :Intuicao %>
  </div>
  <div class="field">
    <%= f.label :Vontade %><br>
    <%= f.number_field :Vontade %>
  </div>
  <div class="field">
    <%= f.label :Presenca %><br>
    <%= f.number_field :Presenca %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

appPlayer/app/views/atributes/edit.html.erb
<h1>Editing Atribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @atribute %> |
<%= link_to 'Back', atributes_path %>

appPlayer/app/views/atributes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Atributes</h1>

<table>
  <thead>
    <tr>
      <th>Forca</th>
      <th>Reflexo</th>
      <th>Saude</th>
      <th>Intuicao</th>
      <th>Vontade</th>
      <th>Presenca</th>
      <th>Player</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atributes.each do |atribute| %>
      <tr>
        <td><%= atribute.Forca %></td>
        <td><%= atribute.Reflexo %></td>
        <td><%= atribute.Saude %></td>
        <td><%= atribute.Intuicao %></td>
        <td><%= atribute.Vontade %></td>
        <td><%= atribute.Presenca %></td>
        <td><%= atribute.player %></td>
        <td><%= link_to 'Show', atribute %></td>
        <td><%= link_to 'Edit', edit_atribute_path(atribute) %></td>
        <td><%= link_to 'Destroy', atribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo atributo', new_atribute_path %>

appPlayer/app/views/atributes/new.html.erb
<h1>New Atribute</h1>

<%= render 'form' %>

<%= link_to 'Back', atributes_path %>

appPlayer/app/views/atributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Forca:</strong>
  <%= @atribute.Forca %>
</p>

<p>
  <strong>Reflexo:</strong>
  <%= @atribute.Reflexo %>
</p>

<p>
  <strong>Saude:</strong>
  <%= @atribute.Saude %>
</p>

<p>
  <strong>Intuicao:</strong>
  <%= @atribute.Intuicao %>
</p>

<p>
  <strong>Vontade:</strong>
  <%= @atribute.Vontade %>
</p>

<p>
  <strong>Presenca:</strong>
  <%= @atribute.Presenca %>
</p>

<p>
  <strong>Player:</strong>
  <%= @atribute.player %>
</p>

<%= link_to 'Edit', edit_atribute_path(@atribute) %> |
<%= link_to 'Back', atributes_path %>

appPlayer/app/views/features/_form.html.erb
<%= form_for(@feature) do |f| %>
  <% if @feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
      <% @feature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :equipamentos %><br>
    <%= f.text_area :equipamentos %>
  </div>
  <div class="field">
    <%= f.label :proficiencias %><br>
    <%= f.text_area :proficiencias %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

appPlayer/app/views/features/edit.html.erb
<h1>Editing Feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %>

appPlayer/app/views/features/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Features</h1>

<table>
  <thead>
    <tr>
      <th>Equipamentos</th>
      <th>Proficiencias</th>
      <th>Player</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @features.each do |feature| %>
      <tr>
        <td><%= feature.equipamentos %></td>
        <td><%= feature.proficiencias %></td>
        <td><%= feature.player %></td>
        <td><%= link_to 'Show', feature %></td>
        <td><%= link_to 'Edit', edit_feature_path(feature) %></td>
        <td><%= link_to 'Destroy', feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novos itens', new_feature_path %>

appPlayer/app/views/features/new.html.erb
<h1>New Feature</h1>

<%= render 'form' %>

<%= link_to 'Back', features_path %>

appPlayer/app/views/features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Equipamentos:</strong>
  <%= @feature.equipamentos %>
</p>

<p>
  <strong>Proficiencias:</strong>
  <%= @feature.proficiencias %>
</p>

<p>
  <strong>Player:</strong>
  <%= @feature.player %>
</p>

<%= link_to 'Edit', edit_feature_path(@feature) %> |
<%= link_to 'Back', features_path %>

appPlayer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppPlayer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

appPlayer/app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :especie %><br>
    <%= f.text_field :especie %>
  </div>
  <div class="field">
    <%= f.label :altura %><br>
    <%= f.text_field :altura %>
  </div>
  <div class="field">
    <%= f.label :peso %><br>
    <%= f.text_field :peso %>
  </div>
  <div class="field">
    <%= f.label :gravidade %><br>
    <%= f.text_field :gravidade %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.text_field :sexo %>
  </div>
  <div class="field">
    <%= f.label :idade %><br>
    <%= f.text_field :idade %>
  </div>
  
  <%= f.fields_for :atribute do |ff| %>
    <div class= "field">
	<%= ff.label :Forca %><br>
	<%= ff.number_field :Forca %>
    </div> 
    <div class= "field">
	<%= ff.label :Reflexo %><br>
	<%= ff.number_field :Reflexo %>
    </div>
    <div class= "field">
	<%= ff.label :Saude %><br>
	<%= ff.number_field :Saude %>
    </div>
    <div class= "field">
	<%= ff.label :Intuicao %><br>
	<%= ff.number_field :Intuicao %>
    </div>
    <div class= "field">
	<%= ff.label :Vontade %><br>
	<%= ff.number_field :Vontade %>
    </div>
    <div class= "field">
	<%= ff.label :Presenca %><br>
	<%= ff.number_field :Presenca %>
    </div>

    <% end %>

    <%= f.fields_for :feature do |ff|%>

    <div class= "field">
	<%= ff.label :equipamentos %><br>
	<%= ff.text_area :equipamentos %>
    </div>

    <div class= "field">
	<%= ff.label :proficiencias %><br>
	<%= ff.text_area:proficiencias %>
    </div>

 <% end %>

 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

appPlayer/app/views/players/edit.html.erb
<h1>Editar Personagem</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @player %> |
<%= link_to 'Retornar', players_path %>

appPlayer/app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(players_path, :method => :get) do %>
  <%= text_field_tag 'procurar..', nil, placeholder: 'Nome ou fragmento..' %>
  <%= submit_tag "Procurar" %>
<% end %>

<h1>Lista de Personagens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Especie</th>
      <th>Altura</th>
      <th>Peso</th>
      <th>Gravidade</th>
      <th>Sexo</th>
      <th>Idade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.especie %></td>
        <td><%= player.altura %></td>
        <td><%= player.peso %></td>
        <td><%= player.gravidade %></td>
        <td><%= player.sexo %></td>
        <td><%= player.idade %></td>
	<% if current_user.email.eql?("hgmoura@yahoo.com") %>
           <td><%= link_to 'Mostrar', player %></td>
           <td><%= link_to 'Editar', edit_player_path(player) %></td>
           <td><%= link_to 'Destruir', player, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
	<% else %>
	    <td><%= link_to 'Mostrar', player %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo personagem', new_player_path %><br>
<%= current_user.email %></li>
<% if user_signed_in? %>
  <li>
  <%= link_to('Desconectar', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Conectar', new_user_session_path)  %>  
  </li>
<% end %>

appPlayer/app/views/players/new.html.erb
<h1>Novo Personagem</h1>

<%= render 'form' %>

<%= link_to 'Retornar', players_path %>

appPlayer/app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Especie:</strong>
  <%= @player.especie %>
</p>

<p>
  <strong>Altura:</strong>
  <%= @player.altura %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @player.peso %>
</p>

<p>
  <strong>Gravidade:</strong>
  <%= @player.gravidade %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @player.sexo %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @player.idade %>
</p>

<p>
  <strong>Forca:</strong>
  <%= @player.atribute.Forca %>
</p>

<p>
  <strong>Reflexo:</strong>
  <%= @player.atribute.Reflexo %>
</p>

<p>
  <strong>Saude:</strong>
  <%= @player.atribute.Saude %>
</p>

<p>
  <strong>Intuicao:</strong>
  <%= @player.atribute.Intuicao %>
</p>

<p>
  <strong>Vontade:</strong>
  <%= @player.atribute.Vontade %>
</p>

<p>
  <strong>Presenca:</strong>
  <%= @player.atribute.Presenca %>
</p>

<p>
  <strong>Equipamentos:</strong>
  <%= @player.feature.equipamentos %>
</p>

<p>
  <strong>Proficiencias:</strong>
  <%= @player.feature.proficiencias %>
</p>

<%= link_to 'Editar', edit_player_path(@player) %> |
<%= link_to 'Retornar', players_path %>

appPlayer/app/views/welcome/index.html.erb
<h1>.::MILLENIA::.</h1>
<p>Campanha escrita por: HGM</p>
<p>Mestre do jogo: HGM</p>
<ul>
   <li><%= link_to "URIAH-10",players_path %></li>
</ul>